/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'peru': RouteRecordInfo<'peru', '/peru', Record<never, never>, Record<never, never>>,
    'peru-administracion-log-usuario': RouteRecordInfo<'peru-administracion-log-usuario', '/peru/administracion/log-usuario', Record<never, never>, Record<never, never>>,
    'peru-administracion-permiso-zonal': RouteRecordInfo<'peru-administracion-permiso-zonal', '/peru/administracion/permiso-zonal', Record<never, never>, Record<never, never>>,
    'peru-consultas-generales': RouteRecordInfo<'peru-consultas-generales', '/peru/consultas/generales', Record<never, never>, Record<never, never>>,
    'peru-consultas-log-pedido': RouteRecordInfo<'peru-consultas-log-pedido', '/peru/consultas/log-pedido', Record<never, never>, Record<never, never>>,
    'peru-procesos-abrir-asistencia': RouteRecordInfo<'peru-procesos-abrir-asistencia', '/peru/procesos/abrir-asistencia', Record<never, never>, Record<never, never>>,
    'peru-procesos-actualizar-dato': RouteRecordInfo<'peru-procesos-actualizar-dato', '/peru/procesos/actualizar-dato', Record<never, never>, Record<never, never>>,
    'peru-procesos-cerrar-asistencia': RouteRecordInfo<'peru-procesos-cerrar-asistencia', '/peru/procesos/cerrar-asistencia', Record<never, never>, Record<never, never>>,
    'peru-procesos-confirmar-inscripcion': RouteRecordInfo<'peru-procesos-confirmar-inscripcion', '/peru/procesos/confirmar-inscripcion', Record<never, never>, Record<never, never>>,
    'peru-procesos-desbloquear-asesora': RouteRecordInfo<'peru-procesos-desbloquear-asesora', '/peru/procesos/desbloquear-asesora', Record<never, never>, Record<never, never>>,
    'peru-procesos-gestionar-posible-asesora': RouteRecordInfo<'peru-procesos-gestionar-posible-asesora', '/peru/procesos/gestionar-posible-asesora', Record<never, never>, Record<never, never>>,
    'peru-procesos-posible-asesora': RouteRecordInfo<'peru-procesos-posible-asesora', '/peru/procesos/posible-asesora', Record<never, never>, Record<never, never>>,
    'peru-procesos-respuesta-incidencias': RouteRecordInfo<'peru-procesos-respuesta-incidencias', '/peru/procesos/respuesta-incidencias', Record<never, never>, Record<never, never>>,
    'peru-reportes-asistencia-conferencia': RouteRecordInfo<'peru-reportes-asistencia-conferencia', '/peru/reportes/asistencia-conferencia', Record<never, never>, Record<never, never>>,
    'peru-reportes-ciclo-pedido': RouteRecordInfo<'peru-reportes-ciclo-pedido', '/peru/reportes/ciclo-pedido', Record<never, never>, Record<never, never>>,
    'peru-reportes-comportamiento-cambios': RouteRecordInfo<'peru-reportes-comportamiento-cambios', '/peru/reportes/comportamiento-cambios', Record<never, never>, Record<never, never>>,
    'peru-reportes-consecutividad': RouteRecordInfo<'peru-reportes-consecutividad', '/peru/reportes/consecutividad', Record<never, never>, Record<never, never>>,
    'peru-reportes-directorio-lider': RouteRecordInfo<'peru-reportes-directorio-lider', '/peru/reportes/directorio-lider', Record<never, never>, Record<never, never>>,
    'peru-reportes-distribucion-consolidado-estado-pedido': RouteRecordInfo<'peru-reportes-distribucion-consolidado-estado-pedido', '/peru/reportes/distribucion/consolidado-estado-pedido', Record<never, never>, Record<never, never>>,
    'peru-reportes-distribucion-estado-pedido-fecha': RouteRecordInfo<'peru-reportes-distribucion-estado-pedido-fecha', '/peru/reportes/distribucion/estado-pedido-fecha', Record<never, never>, Record<never, never>>,
    'peru-reportes-evaluacion-cierre': RouteRecordInfo<'peru-reportes-evaluacion-cierre', '/peru/reportes/evaluacion-cierre', Record<never, never>, Record<never, never>>,
    'peru-reportes-fraccionamiento': RouteRecordInfo<'peru-reportes-fraccionamiento', '/peru/reportes/fraccionamiento', Record<never, never>, Record<never, never>>,
    'peru-reportes-gemmas-acumuladas': RouteRecordInfo<'peru-reportes-gemmas-acumuladas', '/peru/reportes/gemmas-acumuladas', Record<never, never>, Record<never, never>>,
    'peru-reportes-inscripciones': RouteRecordInfo<'peru-reportes-inscripciones', '/peru/reportes/inscripciones', Record<never, never>, Record<never, never>>,
    'peru-reportes-lider-pago': RouteRecordInfo<'peru-reportes-lider-pago', '/peru/reportes/lider-pago', Record<never, never>, Record<never, never>>,
    'peru-reportes-listado-asesora': RouteRecordInfo<'peru-reportes-listado-asesora', '/peru/reportes/listado-asesora', Record<never, never>, Record<never, never>>,
    'peru-reportes-pedido-digitado-pais': RouteRecordInfo<'peru-reportes-pedido-digitado-pais', '/peru/reportes/pedido-digitado-pais', Record<never, never>, Record<never, never>>,
    'peru-reportes-pedido-digitado-region': RouteRecordInfo<'peru-reportes-pedido-digitado-region', '/peru/reportes/pedido-digitado-region', Record<never, never>, Record<never, never>>,
    'peru-reportes-pedido-digitado-zona': RouteRecordInfo<'peru-reportes-pedido-digitado-zona', '/peru/reportes/pedido-digitado-zona', Record<never, never>, Record<never, never>>,
    'peru-reportes-posibles-asesoras': RouteRecordInfo<'peru-reportes-posibles-asesoras', '/peru/reportes/posibles-asesoras', Record<never, never>, Record<never, never>>,
    'peru-reportes-prepedido': RouteRecordInfo<'peru-reportes-prepedido', '/peru/reportes/prepedido', Record<never, never>, Record<never, never>>,
    'peru-reportes-producto-lider': RouteRecordInfo<'peru-reportes-producto-lider', '/peru/reportes/producto-lider', Record<never, never>, Record<never, never>>,
    'peru-reportes-proyeccion-region': RouteRecordInfo<'peru-reportes-proyeccion-region', '/peru/reportes/proyeccion-region', Record<never, never>, Record<never, never>>,
    'peru-reportes-proyeccion-zona': RouteRecordInfo<'peru-reportes-proyeccion-zona', '/peru/reportes/proyeccion-zona', Record<never, never>, Record<never, never>>,
    'peru-reportes-referidos': RouteRecordInfo<'peru-reportes-referidos', '/peru/reportes/referidos', Record<never, never>, Record<never, never>>,
    'peru-reportes-seguimiento-cierre-region': RouteRecordInfo<'peru-reportes-seguimiento-cierre-region', '/peru/reportes/seguimiento-cierre-region', Record<never, never>, Record<never, never>>,
    'peru-reportes-seguimiento-cierre-zona': RouteRecordInfo<'peru-reportes-seguimiento-cierre-zona', '/peru/reportes/seguimiento-cierre-zona', Record<never, never>, Record<never, never>>,
    'peru-reportes-semaforo-lider': RouteRecordInfo<'peru-reportes-semaforo-lider', '/peru/reportes/semaforo-lider', Record<never, never>, Record<never, never>>,
    'peru-reportes-simulador-cobranza': RouteRecordInfo<'peru-reportes-simulador-cobranza', '/peru/reportes/simulador-cobranza', Record<never, never>, Record<never, never>>,
    'peru-reportes-status-mgz': RouteRecordInfo<'peru-reportes-status-mgz', '/peru/reportes/status-mgz', Record<never, never>, Record<never, never>>,
    'peru-reportes-tracking-zona': RouteRecordInfo<'peru-reportes-tracking-zona', '/peru/reportes/tracking-zona', Record<never, never>, Record<never, never>>,
    'peru-reportes-visitas': RouteRecordInfo<'peru-reportes-visitas', '/peru/reportes/visitas', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
