export default [
  { 
    heading: 'Procesos', 
    subject: 'colombia/proc', 
    action: 'colombia/proc',
  },
  { 
    title: 'Abrir asistencia', 
    to: { name: 'procesos-abrir-asistencia' },
    icon: 'tabler-pencil-up',
    subject: 'colombia/proc_come_abri_asis', 
    action: 'colombia/proc',
  },
  { 
    title: 'Actualizar dato asesora', 
    to: { name: 'procesos-actualizar-dato' },
    icon: 'tabler-edit',
    subject: 'colombia/proc_come_actu_dato_simp', 
    action: 'colombia/proc',
  },
  { 
    title: 'Cerrar asistencia', 
    to: { name: 'procesos-cerrar-asistencia' },
    icon: 'tabler-pencil-off',
    subject: 'colombia/proc_come_cerr_asis', 
    action: 'colombia/proc',
  },
  { 
    title: 'Confirmar incorporación digital', 
    to: { name: 'procesos-confirmar-inscripcion' },
    icon: 'tabler-user-plus',
    subject: 'colombia/proc_come_conf_insc_movi', 
    action: 'colombia/proc',
  },
  { 
    title: 'Desbloquear asesora', 
    to: { name: 'procesos-desbloquear-asesora' },
    icon: 'tabler-lock-open',
    subject: 'colombia/proc_come_desb_ases', 
    action: 'colombia/proc',
  },
  { 
    title: 'Gestionar posible asesora', 
    to: { name: 'procesos-gestionar-posible-asesora' },
    icon: 'tabler-clock-code',
    subject: 'colombia/proc_come_gest_posi_ases', 
    action: 'colombia/proc',
  },
  { 
    title: 'Gestionar vacaciones', 
    to: { name: 'procesos-gestionar-vacaciones' },
    icon: 'tabler-clock-code',
    subject: 'colombia/proc_come_gest_vaca', 
    action: 'colombia/proc',
  },
  { 
    title: 'Grabar pedido', 
    to: { name: 'procesos-grabar-pedido' },
    icon: 'tabler-shopping-cart',
    subject: 'colombia/proc_come_grab_pedi', 
    action: 'colombia/proc',
  },
  { 
    title: 'Registro posible asesora', 
    to: { name: 'procesos-posible-asesora' },
    icon: 'tabler-rotate-clockwise',
    subject: 'colombia/proc_come_posi_ases', 
    action: 'colombia/proc',
  },
  { 
    title: 'Respuesta Incidencias', 
    to: { name: 'procesos-respuesta-incidencias' },
    icon: 'tabler-clock-24',
    subject: 'colombia/proc_cart_resp_inci_diar', 
    action: 'colombia/proc',
  },
  { 
    title: 'Producto zona', 
    to: { name: 'procesos-producto-zona' },
    icon: 'tabler-clock-24',
    subject: 'colombia/proc_come_prod_zona', 
    action: 'colombia/proc',
  },
  { 
    title: 'Solicitud recodificacion', 
    to: { name: 'procesos-solicitar-recodificacion' },
    icon: 'tabler-clock-24',
    subject: 'colombia/proc_come_soli_reco', 
    action: 'colombia/proc',
  },
  { 
    title: 'Solicitud vacaciones', 
    to: { name: 'procesos-solicitar-vacaciones' },
    icon: 'tabler-clock-24',
    subject: 'colombia/proc_come_soli_vaca', 
    action: 'colombia/proc',
  },
  { 
    title: 'Status entrega MGZ', 
    to: { name: 'procesos-status-mgz' },
    icon: 'tabler-clock-24',
    subject: 'colombia/proc_come_stat_mate', 
    action: 'colombia/proc',
  },
  
  { 
    title: 'Vinculación digital', 
    to: { name: 'procesos-vinculacion-digital' },
    icon: 'tabler-world-up',
    subject: 'colombia/proc_come_vinc_digi', 
    action: 'colombia/proc',
  },
]
