export default [
  { 
    heading: 'Reportes', 
    subject: 'colombia/repo', 
    action: 'colombia/repo',
  },
  { 
    title: 'Asistencia conferencia', 
    to: { name: 'reportes-asistencia-conferencia' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_asis_conf', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Ciclo pedido', 
    to: { name: 'reportes-ciclo-pedido' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_cicl_pedi', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Comportamiento C&D', 
    to: { name: 'reportes-comportamiento-cambios' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_comp_canj_devo', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Consecutividad asesoras nuevas', 
    to: { name: 'reportes-consecutividad' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_cons_ases_nuev', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Consulta Asignacion Sectores', 
    to: { name: 'reportes-repo-cons-asig-sect' },
    icon: 'tabler-report',
    subject: 'colombia/repo_cons_asig_sect', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Directorio lider', 
    to: { name: 'reportes-repo-lide-refe' },
    icon: 'tabler-report',
    subject: 'colombia/repo_lide_refe', 
    action: 'colombia/repo', 
  },
  { 
    heading: 'Reportes | Distribucion', 
    subject: 'colombia/repo_dist', 
    action: 'colombia/repo_dist',
  },
  { 
    title: 'Consolidado estado pedido', 
    to: { name: 'reportes-distribucion-consolidado-estado-pedido' },
    icon: 'tabler-report',
    subject: 'colombia/repo_dist_cons_esta_pedi', 
    action: 'colombia/repo_dist', 
  },
  { 
    title: 'Estado pedido fecha', 
    to: { name: 'reportes-distribucion-estado-pedido-fecha' },
    icon: 'tabler-report',
    subject: 'colombia/repo_dist_esta_pedi_fech', 
    action: 'colombia/repo_dist', 
  },
  // { 
  //   title: 'Fraccionamiento', 
  //   to: { name: 'reportes-fraccionamiento' },
  //   icon: 'tabler-report',
  //   subject: 'colombia/repo_come_sald_cart', 
  //   action: 'colombia/repo', 
  // },
  { 
    title: 'Gemmas acumuladas', 
    to: { name: 'reportes-gemmas-acumuladas' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_gemm_acum', 
    action: 'colombia/repo', 
  },
  { 
    heading: 'Reportes | Indicadores de gestión', 
    subject: 'colombia/repo_indi', 
    action: 'colombia/repo_indi',
  },
  { 
    title: 'Evaluación cierre', 
    to: { name: 'reportes-evaluacion-cierre' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_eval_cier', 
    action: 'colombia/repo_indi', 
  },
  { 
    title: 'Lideres ganadoras zona', 
    to: { name: 'reportes-lider-ganadoras-zona' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_lide_gana_zona', 
    action: 'colombia/repo_indi', 
  },
  { 
    title: 'Lideres ganadoras región', 
    to: { name: 'reportes-lider-ganadoras-region' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_lide_gana_regi', 
    action: 'colombia/repo_indi', 
  },
  {   
    title: 'Proyección región', 
    to: { name: 'reportes-proyeccion-region' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_proy_camp_regi', 
    action: 'colombia/repo_indi', 
  },
  { 
    title: 'Proyección zona', 
    to: { name: 'reportes-proyeccion-zona' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_proy_camp', 
    action: 'colombia/repo_indi', 
  },
  { 
    title: 'Seguimiento cierre país', 
    to: { name: 'reportes-seguimiento-cierre-pais' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_segu_cier_camp_pais', 
    action: 'colombia/repo_indi', 
  },
  { 
    title: 'Seguimiento cierre region', 
    to: { name: 'reportes-seguimiento-cierre-region' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_segu_cier_camp_regi', 
    action: 'colombia/repo_indi', 
  },
  { 
    title: 'Seguimiento cierre zona', 
    to: { name: 'reportes-seguimiento-cierre-zona' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_segu_cier_camp', 
    action: 'colombia/repo_indi', 
  },
  { 
    title: 'Semaforo lider', 
    to: { name: 'reportes-semaforo-lider' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_sema_lide', 
    action: 'colombia/repo_indi', 
  },
  { 
    title: 'Semaforo zona', 
    to: { name: 'reportes-semaforo-zona' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_sema_zona', 
    action: 'colombia/repo_indi', 
  },  
  // { 
  //   title: 'Incorporación digital', 
  //   to: { name: 'reportes-inscripciones' },
  //   icon: 'tabler-report',
  //   subject: 'colombia/repo_come_insc_movi', 
  //   action: 'colombia/repo', 
  // },
  // { 
  //   title: 'Lider pago', 
  //   to: { name: 'reportes-lider-pago' },
  //   icon: 'tabler-report',
  //   subject: 'colombia/repo_come_lide_pago', 
  //   action: 'colombia/repo', 
  // },
  { 
    title: 'Listado asesora', 
    to: { name: 'reportes-listado-asesora' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_list_ases', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Pedido digitado pais', 
    to: { name: 'reportes-pedido-digitado-pais' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_pedi_digi_pais', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Pedido digitado región', 
    to: { name: 'reportes-pedido-digitado-region' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_pedi_digi_regi', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Pedido digitado zona', 
    to: { name: 'reportes-pedido-digitado-zona' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_pedi_digi', 
    action: 'colombia/repo', 
  },
  // { 
  //   title: 'Posible asesora', 
  //   to: { name: 'reportes-posibles-asesoras' },
  //   icon: 'tabler-report',
  //   subject: 'colombia/repo_come_posi_ases', 
  //   action: 'colombia/repo', 
  // },
  { 
    title: 'Azzorti Proyecta', 
    to: { name: 'reportes-prepedido' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_prep_pedi', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Producto lider', 
    to: { name: 'reportes-producto-lider' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_prod_lide', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Referidos', 
    to: { name: 'reportes-referidos' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_refe', 
    action: 'colombia/repo', 
  },
  // { 
  //   title: 'Segmentación asesora', 
  //   to: { name: 'reportes-segmentacion-asesora' },
  //   icon: 'tabler-report',
  //   subject: 'colombia/repo_come_segm_ases', 
  //   action: 'colombia/repo', 
  // },
  { 
    title: 'Simulador de cobranza', 
    to: { name: 'reportes-simulador-cobranza' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_simu_cobr', 
    action: 'colombia/repo', 
  },
  // { 
  //   title: 'Solicitud recodificación', 
  //   to: { name: 'reportes-solicitud-recodificacion' },
  //   icon: 'tabler-report',
  //   subject: 'colombia/repo_come_soli_reco', 
  //   action: 'colombia/repo', 
  // },
  { 
    title: 'Status MGZ', 
    to: { name: 'reportes-status-mgz' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_stat_mgzz', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Tracking zona', 
    to: { name: 'reportes-tracking-zona' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_trac_zona', 
    action: 'colombia/repo', 
  },
  { 
    heading: 'Reportes | Vacaciones', 
    subject: 'colombia/repo_vaca', 
    action: 'colombia/repo_vaca',
  },
  { 
    title: 'Consolidado', 
    to: { name: 'reportes-vacaciones-consolidado' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_soli_vaca', 
    action: 'colombia/repo_vaca', 
  },
  { 
    title: 'Pendientes región', 
    to: { name: 'reportes-vacaciones-pendientes' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_vaca_pend', 
    action: 'colombia/repo_vaca', 
  },
  { 
    title: 'Vinculación digital', 
    to: { name: 'reportes-vinculacion-digital' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_vinc_digi', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Azzorti maps', 
    to: { name: 'reportes-visitas' },
    icon: 'tabler-report',
    subject: 'colombia/repo_come_visi', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Concurso Sueños', 
    to: { name: 'reportes-concurso-suenos' },
    icon: 'tabler-report',
    subject: 'colombia/repo_conc_dupr', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Impresion Saldos Cartera', 
    to: { name: 'reportes-impr-sald-cart' },
    icon: 'tabler-report',
    subject: 'colombia/impr_sald_cart', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Faltante Anunciado', 
    to: { name: 'reportes-falt-anun' },
    icon: 'tabler-report',
    subject: 'colombia/repo_falt_anun', 
    action: 'colombia/repo', 
  },
  { 
    title: 'App Movil', 
    to: { name: 'reportes-reporte-app-movil' },
    icon: 'tabler-report',
    subject: 'colombia/repo_app_movi', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Reporte PBIE', 
    to: { name: 'reportes-reporte-pbie' },
    icon: 'tabler-report',
    subject: 'colombia/menu_repo_pbie', 
    action: 'colombia/repo', 
  },
  { 
    title: 'Vinculacion', 
    to: { name: 'reportes-reporte-vinculacion' },
    icon: 'tabler-report',
    subject: 'colombia/repo_vinc_digi', 
    action: 'colombia/repo', 
  },
]
