export default [
  { 
    heading: 'Procesos', 
    subject: 'colombia/proc', 
    action: 'colombia/proc',
  },
  { 
    title: 'Abrir asistencia', 
    to: 'procesos-abrir-asistencia',
    icon: { icon: 'tabler-pencil-up' },
    subject: 'colombia/proc_come_abri_asis', 
    action: 'colombia/proc_come_abri_asis',
  },
  { 
    title: 'Actualizar dato simple', 
    to: 'procesos-actualizar-dato',
    icon: { icon: 'tabler-edit' },
    subject: 'colombia/proc_come_actu_dato_simp', 
    action: 'colombia/proc_come_actu_dato_simp',
  },
  { 
    title: 'Cerrar asistencia', 
    to: 'procesos-cerrar-asistencia',
    icon: { icon: 'tabler-pencil-off' },
    subject: 'colombia/proc_come_cerr_asis', 
    action: 'colombia/proc_come_cerr_asis',
  },
  { 
    title: 'Confirmación inscripción', 
    to: 'procesos-confirmar-inscripcion',
    icon: { icon: 'tabler-user-plus' },
    subject: 'colombia/proc_come_conf_insc_movi', 
    action: 'colombia/proc_come_conf_insc_movi',
  },
  { 
    title: 'Desbloquear asesora', 
    to: 'procesos-desbloquear-asesora',
    icon: { icon: 'tabler-lock-open' },
    subject: 'colombia/proc_come_desb_ases', 
    action: 'colombia/proc_come_desb_ases',
  },
  { 
    title: 'Gestionar posible asesora', 
    to: 'procesos-gestionar-posible-asesora',
    icon: { icon: 'tabler-clock-code' },
    subject: 'colombia/proc_come_gest_posi_ases', 
    action: 'colombia/proc_come_gest_posi_ases',
  },
  { 
    title: 'Gestionar vacaciones', 
    to: 'procesos-gestionar-vacaciones',
    icon: { icon: 'tabler-clock-code' },
    subject: 'colombia/proc_come_gest_vaca', 
    action: 'colombia/proc_come_gest_vaca',
  },
  { 
    title: 'Grabar pedido', 
    to: 'procesos-grabar-pedido',
    icon: { icon: 'tabler-shopping-cart' },
    subject: 'colombia/proc_come_grab_pedi', 
    action: 'colombia/proc_come_grab_pedi',
  },
  { 
    title: 'Registro posible asesora', 
    to: 'procesos-posible-asesora',
    icon: { icon: 'tabler-rotate-clockwise' },
    subject: 'colombia/proc_come_posi_ases', 
    action: 'colombia/proc_come_posi_ases',
  },
  { 
    title: 'Respuesta Incidencias', 
    to: 'procesos-respuesta-incidencias',
    icon: { icon: 'tabler-clock-24' },
    subject: 'colombia/proc_cart_resp_inci_diar', 
    action: 'colombia/proc_cart_resp_inci_diar',
  },
  { 
    title: 'Producto zona', 
    to: 'procesos-producto-zona',
    icon: { icon: 'tabler-clock-24' },
    subject: 'colombia/proc_come_prod_zona', 
    action: 'colombia/proc_come_prod_zona',
  },
  { 
    title: 'Solicitud recodificacion', 
    to: 'procesos-solicitar-recodificacion',
    icon: { icon: 'tabler-clock-24' },
    subject: 'colombia/proc_come_soli_reco', 
    action: 'colombia/proc_come_soli_reco',
  },
  { 
    title: 'Solicitud vacaciones', 
    to: 'procesos-solicitar-vacaciones',
    icon: { icon: 'tabler-clock-24' },
    subject: 'colombia/proc_come_soli_vaca', 
    action: 'colombia/proc_come_soli_vaca',
  },
  { 
    title: 'Vinculación digital', 
    to: 'procesos-vinculacion-digital',
    icon: { icon: 'tabler-world-up' },
    subject: 'colombia/proc_come_vinc_digi', 
    action: 'colombia/proc_come_vinc_digi',
  },
  { 
    title: 'Consolidado Campaña', 
    to: 'procesos-consolidado-campana',
    icon: { icon: 'tabler-world-up' },
    subject: 'colombia/proc_tab_cons', 
    action: 'colombia/proc_tab_cons',
  },
  { 
    title: 'Aprobacion ingresos digitales', 
    to: 'procesos-aprob-ingr-digitales',
    icon: { icon: 'tabler-world-up' },
    subject: 'colombia/form_veri_pre_ases',  
    action: 'colombia/form_veri_pre_ases',
  }, 
  { 
    title: 'Asignacion reingreso lider', 
    to: 'procesos-asigna-reingreso',
    icon: { icon: 'tabler-world-up' },
    subject: 'colombia/asi_lide_rein',  
    action: 'colombia/asi_lide_rein',
  }, 
  { 
    title: 'Pre Pedido', 
    to: 'procesos-pre-pedido',
    icon: { icon: 'tabler-world-up' },
    subject: 'colombia/pre_pedido',  
    action: 'colombia/pre_pedido',
  },
]
